<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>SulfurLauncher.Bedrock.Xbox</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SulfurLauncher.Localization\SulfurLauncher.Localization.csproj" />
  </ItemGroup>

</Project>
